export enum CancellationStatus {
  DRIVER_CANCELLED = 'DRIVER_CANCELLED',
  USER_CANCELLED = 'USER_CANCELLED',
  SYSTEM_CANCELLED = 'SYSTEM_CANCELLED',
}

export enum TripStatus {
  TRIP_BOOKED = 'TRIP_BOOKED',
  TRIP_ASSIGNED = 'TRIP_ASSIGNED',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  DRIVER_ACCEPTED = 'DRIVER_ACCEPTED',
  DRIVER_DECLINED = 'DRIVER_DECLINED',
  TRIP_RE_ASSIGN = 'TRIP_RE_ASSIGN',
  TRIP_STARTED = 'TRIP_STARTED',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
  TRIP_CANCELLED_BY_USER = 'TRIP_CANCELLED_BY_USER',
  TRIP_CANCELLED_BY_DRIVER = 'TRIP_CANCELLED_BY_DRIVER',
  TRIP_CANCELLED = 'TRIP_CANCELLED',
  /** No driver could be confirmed in time, or assignment flow ended in an invalid state. */
  SYSTEM_CANCELLED = 'SYSTEM_CANCELLED',
}